### ISSUE TITLE
Make performance benchmark a separate repository

### ISSUE THREAD

**Issue by greenlaw110** [networknt/light-example-4j#22]
It would be good to move `performance` out of `light-java-example` I believe a lot of person fork the repository only because of the `performance` benchmark set

**Comment by stevehu** [comment]
You are right. This is unexpected and I will do it once I have time. I have too many repos and it is very hard to manage these days:)

**Comment by greenlaw110** [comment]
Just FYI, I've copied your code and created a separate repository at https://github.com/greenlaw110/simple-webframework-benchmark. And yes the disclaim of the original of the project is declared in the README.md file

**Comment by stevehu** [comment]
Cool. I saw your test results are different than mine as you have a faster computer. It is good we have to result sets so people can understand the impact of OS and hardware to performance. It is better to test it by themselves as source code is available. Great work!!!

**Comment by stevehu** [comment]
@IRus and I are working on dockerizing these test cases so that users can run the test on their own. I think it is a good idea to have a separate repo to do this.
