### ISSUE TITLE
Singleton Resources

### ISSUE THREAD

**Issue by davidnqd** [networknt/light-example-4j#25]
For the performance tests. I am not sure if it is fair for the containers which use dependency injection to not use @Singleton or similar annotation to prevent redundant instances of the resource.

Looking specifically at: https://github.com/networknt/light-java-example/blob/master/performance/dropwizard/src/main/java/com/mycompany/HelloWorldResource.java

**Comment by stevehu** [comment]
@davidnqd I am not familiar with dropwizard and the performance folder has been moved to https://github.com/networknt/microservices-framework-benchmark. Could you please submit a pull request so that I can retest it. Thanks a lot.

**Comment by stevehu** [comment]
I have removed performance folder from this repo. Thanks.

**Comment by davidnqd** [comment]
Absolutely, will do.
