### ISSUE TITLE
how can I use "docker exec" for light-4j containers?

### ISSUE THREAD

**Issue by lanphan** [networknt/light-example-4j#28]
Hi @stevehu ,
I can start some example light-4j from my localhost, but for docker container, I tried to "docker exec" into its container but no lucky.
I see that containers of light-4j inherits from insideo:uc-linux, and I found it support bash command line, I tried these things below:
docker exec -it <container id> bash
docker exec -it <container id> /bin/bash
docker exec -it <container id> /tools/bash

Can you shed some light on it? Thanks.

**Comment by stevehu** [comment]
@lanphan As we are using Alpine Linux as our base image, it doesn't have bash but only sh.

docker exec -it containerId sh

**Comment by lanphan** [comment]
Thanks, it works.
