### ISSUE TITLE
petstore example in README.md does not run

### ISSUE THREAD

**Issue by retinaburn** [networknt/light-example-4j#34]
It looks like the petstore example no longer runs with the described command:
`java -jar target/codegen-cli.jar -f light-rest-4j -o ~/networknt/light-example-4j/rest/petstore -m ~/networknt/model-config/rest/petstore/swagger.json -c ~/networknt/model-config/rest/petstore/config.json`

It looks like theconfig.json and swagger.json are at least in a 2.0.0 path under petstore.  Even with that change though it fails.

The documentation on https://networknt.github.io/light-4j/example/petstore/ is also incomplete.

**Comment by stevehu** [comment]
We are in a process to consolidate documents from individual project to a central location and the tutorials for petstore are here. 

Petstore based on Swagger 2.0 specification

https://doc.networknt.com/tutorial/rest/swagger/petstore/

Petstore based on OpenAPI 3.0 specification

https://doc.networknt.com/tutorial/rest/openapi/petstore/

I will update the README.md to link to the above locations. Thanks for bringing it up.

**Comment by stevehu** [comment]
The following readme files are updated. 

https://github.com/networknt/light-example-4j/tree/master/rest/swagger/petstore
https://github.com/networknt/light-example-4j/tree/master/rest/openapi/petstore

**Comment by stevehu** [comment]
The following document site will be removed once all contents are migrated to light-doc repo 
https://github.com/networknt/light-4j/issues/139

https://networknt.github.io/light-4j/
