### ISSUE TITLE
Rest petstore openapi example dependencies

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-example-4j#48]
Just wondering where the source is for these dependencies if I want to build locally:
https://github.com/networknt/light-example-4j/blob/master/rest/openapi/petstore/pom.xml#L161-L175

I know that the 1.5.8 version of each are uploaded to maven central, so there is no issue with building.. but from the develop branch, 1.5.9 is not available. Everything still works in the develop branch if those are updated to 1.5.8 so it's not a big issue.

**Comment by stevehu** [comment]
These three jars are for OpenAPI 3.0 specification and it is part of light-rest-4j. Also there is another extra jar that need to be built locally which is openapi-parser. As OpenAPI 3.0 spec is very new, there is no suitable parser on the market so we have to build one.

**Comment by stevehu** [comment]
We now have a new project called light-bot, most team members are using it to build there local environment from develop branch with customized config files. 

https://doc.networknt.com/tool/light-bot/

https://doc.networknt.com/tutorial/bot/

**Comment by NicholasAzar** [comment]
Ahh don't know how i missed those there! sorry & thanks

I looked at light-bot a while ago and didn't dig too much after i saw in the readme that it was for linux only and i currently do most my development on windows.
I'm just trying to build a graphql endpoint overlaying one or more rest endpoints so it seems basic enough to not require any type of build automation tooling. I could be wrong though as i admit to not knowing the full extent to what light-bot can be used for.

**Comment by stevehu** [comment]
light-bot is a framework that can plug in different configurable executors to fulfill tasks in DevOps. Currently, all built-in executors are for Mac and Linux. However, it should work if someone creates Windows corresponding executors. It is just an automation framework that can be used anywhere not just limited on devops servers. Fully distributed DevOps or DevOps as code.
