### ISSUE TITLE
build a client sample to call restful endpoint to gt PDF file by using light-4j client module

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-example-4j#603]
Using light-4j client module to call the endpoint with return pdf bytebuffer.

**Comment by stevehu** [comment]
I double-checked the light-4j client module and you are right. It handles the response body as a string in all callback methods. We should add callback methods that can handle the binary/bytebuffer for PDF and other types. I have created a PR from your branch and I think we need to fix the light-4j client module first. Would you be able to submit a PR on the light-4j repo? Thanks.

**Comment by chenyan71** [comment]
I think the callback has been there for Http2Client and we had sample already for binary format:

https://github.com/networknt/light-example-4j/tree/master/client/pdf

We can close this issue

**Comment by stevehu** [comment]
Yes. We can close it.
