### ISSUE TITLE
Startup failure if change the package name of the startup hook

### ISSUE THREAD

**Issue by PeterKieu** [networknt/light-example-4j#661]
**Source**: https://github.com/networknt/light-example-4j/tree/release/kafka/stream-query
**Action**: 
- Change the package name of the startup hook from com.networknt.kafka to com.yourorg.kafka
- Update the service.yml startup hook path from - com.networknt.kafka.UserQueryStartupHook to - com.yourorg.kafka.UserQueryStartupHook

**Issue**: Cannot run the code with Kafka Streams

**Comment by stevehu** [comment]
Both the release branch and master branch can be started without any issue on my desktop. Are you sure you have the confluent platform started?

**Comment by PeterKieu** [comment]
I use plain Apache Kafka package and It runs well. I also copy this startup light-kafka streams to another project, and get same issue. The producer-comsumer example does not get this issue even if I change all package name!
My enviroment is MacOS x86/ARM M1, Maven.

**Comment by stevehu** [comment]
If it works before you update the package name, that means something is wrong with your updates. Please double-check your updates.

**Comment by PeterKieu** [comment]
OK, I think that the issue relates to  a linking problem for maven and gradle using cache repositories or compiled cache lib.
Before update code, .yml, I clean all cache, then update, then build and run.
The issue goes away!
Thanks

**Comment by PeterKieu** [comment]
The issue is logback does not show info for other package rather than com.networknt.kafka:
<logger name="com.networknt.kafka" level="debug" additivity="false">
        <appender-ref ref="stdout"/>
    </logger>

To show the startup log info change, e.g:
<logger name="io.kaio.kafka" level="debug" additivity="false">
        <appender-ref ref="stdout"/>
    </logger>
