### ISSUE TITLE
Where are the models generated used in any example?

### ISSUE THREAD

**Issue by 243826** [networknt/light-example-4j#86]
I am wondering if there is an example where Pet and Error models are used. The handlers I saw deal with raw json... kind of defeats the purpose of the models. 

I am sure I am missing something... kindly point it out.

**Comment by stevehu** [comment]
The petstore is used to test the generator most of the times and it is not fully implemented. If you want to see real examples, please take a look at the light-oauth2 repository.

**Comment by 243826** [comment]
I looked at the oauth repo as well. What i am looking for is an example where the request parameters are converted to POJOs and responses are sent as POJOs. I thought that would be nice since we are generating those types.

Apologies if I was not thorough to find out the example even though it existed in oauth2 repo.

**Comment by stevehu** [comment]
https://github.com/networknt/light-oauth2/blob/master/client/src/main/java/com/networknt/oauth/client/handler/Oauth2ClientPostHandler.java#L32

https://github.com/networknt/light-oauth2/blob/master/client/src/main/java/com/networknt/oauth/client/handler/Oauth2ClientPostHandler.java#L61

Take a look at the above lines for converting the body to POJO and return a POJO.

**Comment by 243826** [comment]
Thank you!
