### ISSUE TITLE
gen fail

### ISSUE THREAD

**Issue by orangeyts** [networknt/light-example-4j#90]
java -jar target/codegen-cli.jar -f light-rest-4j -o ~/networknt/light-example-4j/rest/petstore -m ~/networknt/model-config/rest/petstore/swagger.json -c ~/networknt/model-config/rest/petstore/config.json

as blow:

[root@localhost codegen-cli]# java -jar target/codegen-cli.jar -f light-rest-4j -o ~/networknt/light-example-4j/rest/petstore -m ~/networknt/model-config/rest/petstore/swagger.json -c ~/networknt/model-config/rest/petstore/config.json
light-rest-4j /root/networknt/model-config/rest/petstore/swagger.json /root/networknt/model-config/rest/petstore/config.json /root/networknt/light-example-4j/rest/petstore
11:46:18.099 [main] INFO com.networknt.config.Config - daily config cache refresh
11:46:18.111 [main] INFO com.networknt.config.Config - Unable to load config from externalized folder for service.yml in 
11:46:18.112 [main] INFO com.networknt.config.Config - Trying to load config from classpath directory for file service.yml
11:46:18.114 [main] INFO com.networknt.config.Config - Config loaded from default folder for service.yml
11:46:18.118 [main] INFO com.networknt.config.Config - Unable to load config from externalized folder for values.yml in 
11:46:18.118 [main] INFO com.networknt.config.Config - Trying to load config from classpath directory for file values.yml
11:46:18.118 [main] INFO com.networknt.config.Config - Unable to load config values.yml. Looking for the same file name with extension yaml...
11:46:18.119 [main] INFO com.networknt.config.Config - Unable to load config from externalized folder for values.yaml in 
11:46:18.119 [main] INFO com.networknt.config.Config - Trying to load config from classpath directory for file values.yaml
11:46:18.119 [main] INFO com.networknt.config.Config - Unable to load config values.yaml. Looking for the same file name with extension json...
11:46:18.119 [main] INFO com.networknt.config.Config - Unable to load config from externalized folder for values.json in 
11:46:18.119 [main] INFO com.networknt.config.Config - Trying to load config from classpath directory for file values.json
Unable to load config 'values' with extension yml, yaml and json from external config, application config and module config. Please ignore this message if you are sure that your application is not using this config file.
11:46:18.120 [main] INFO com.networknt.config.Config - Unable to load config from externalized folder for config.yml in 
11:46:18.120 [main] INFO com.networknt.config.Config - Trying to load config from classpath directory for file config.yml
11:46:18.120 [main] INFO com.networknt.config.Config - Config loaded from default folder for config.yml
Invalid framework: light-rest-4j
avaliable frameworks:
	light-hybrid-4j-server
	light-graphql-4j
	openapi
	light-hybrid-4j-service
	eventuate-rest
	openapikotlin
	swagger

**Comment by orangeyts** [comment]
maybe need a config server ?

**Comment by orangeyts** [comment]
sorry lost doc
from https://doc.networknt.com/tutorial/rest/swagger/petstore/environment/

**Comment by stevehu** [comment]
@orangeyts The framework should be openapi, swagger or openapikotlin. We used to have light-rest-4j as the framework but changed it to openapi and swagger. Recently, the openapikotlin was added. I am wondering if you could let me know where you find the command line that still contains light-rest-4j. We need to update the document to make sure nobody use it anymore. Thanks.
